= Building an AI-driven product recommender with Red Hat OpenShift AI

Welcome to the Building an AI-driven product recommender with Red Hat OpenShift AI workshop!

== What you'll learn

In this workshop, you will:

* Understand different types of transformer models and considerations for their optimal use
* Learn how to design and train a custom AI model that makes intelligent product recommendations
* Learn how to use LLMs to automatically generate product review summaries
* Learn how to build and monitor Kubeflow pipelines
* Learn how to setup the Red Hat inference server and the benefits it provides
* Learn how to use the OpenShift AI FEAST feature store to manage all your AI model data

== Who this is for

This workshop is designed for developers, architects and platform engineers who want to learn to build and use AI models, data pipelines, inference servers and feature stores to build a product recommender.

**Experience level**: Intermediate and advanced

== Prerequisites

Before starting this workshop, you should have:

* Basic understanding of machine learning concepts and AI models
* Familiarity with Kubernetes and containerization
* Experience with Python programming
* Access to Red Hat OpenShift AI environment (this is provided for you automatically if you started this showroom on the Red Hat Developer Platform!)

== Workshop environment

You will have access to a complete Red Hat OpenShift AI environment with pre-configured components for building AI-driven applications.

You will have access to:

* OpenShift cluster: {openshift_console_url}
* Username: {user}
* Password: {password}

NOTE: All environment details and credentials are available in the lab interface.

== Estimated time

This workshop will take approximately **1 hour** to complete.

You can work at your own pace.

== Let's get started!

Login to the console using the above credentials and the login screen you see on the right. 
